/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface CommentResponseDto
 */
export interface CommentResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    threadId: string;
    /**
     * 
     */
    body: string;
    /**
     * 
     */
    authorId: string;
    /**
     * 
     */
    author: string;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CommentResponseDto interface.
 */
export function instanceOfCommentResponseDto(value: object): value is CommentResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CommentResponseDtoFromJSON(json: any): CommentResponseDto {
    return CommentResponseDtoFromJSONTyped(json, false);
}

export function CommentResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'threadId': json['threadId'],
        'body': json['body'],
        'authorId': json['authorId'],
        'author': json['author'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function CommentResponseDtoToJSON(json: any): CommentResponseDto {
    return CommentResponseDtoToJSONTyped(json, false);
}

export function CommentResponseDtoToJSONTyped(value?: CommentResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'threadId': value['threadId'],
        'body': value['body'],
        'authorId': value['authorId'],
        'author': value['author'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

