/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentDto
 */
export interface CreateCommentDto {
    /**
     * 
     */
    body: string;
}

/**
 * Check if a given object implements the CreateCommentDto interface.
 */
export function instanceOfCreateCommentDto(value: object): value is CreateCommentDto {
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CreateCommentDtoFromJSON(json: any): CreateCommentDto {
    return CreateCommentDtoFromJSONTyped(json, false);
}

export function CreateCommentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
    };
}

export function CreateCommentDtoToJSON(json: any): CreateCommentDto {
    return CreateCommentDtoToJSONTyped(json, false);
}

export function CreateCommentDtoToJSONTyped(value?: CreateCommentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
    };
}

