/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateThreadDto
 */
export interface CreateThreadDto {
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    body: string;
}

/**
 * Check if a given object implements the CreateThreadDto interface.
 */
export function instanceOfCreateThreadDto(value: object): value is CreateThreadDto {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function CreateThreadDtoFromJSON(json: any): CreateThreadDto {
    return CreateThreadDtoFromJSONTyped(json, false);
}

export function CreateThreadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateThreadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': json['body'],
    };
}

export function CreateThreadDtoToJSON(json: any): CreateThreadDto {
    return CreateThreadDtoToJSONTyped(json, false);
}

export function CreateThreadDtoToJSONTyped(value?: CreateThreadDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'body': value['body'],
    };
}

