/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThreadResponseDto } from './ThreadResponseDto';
import {
    ThreadResponseDtoFromJSON,
    ThreadResponseDtoFromJSONTyped,
    ThreadResponseDtoToJSON,
    ThreadResponseDtoToJSONTyped,
} from './ThreadResponseDto';
import type { PaginationMetaDto } from './PaginationMetaDto';
import {
    PaginationMetaDtoFromJSON,
    PaginationMetaDtoFromJSONTyped,
    PaginationMetaDtoToJSON,
    PaginationMetaDtoToJSONTyped,
} from './PaginationMetaDto';

/**
 * 
 * @export
 * @interface PaginatedThreadsResponseDto
 */
export interface PaginatedThreadsResponseDto {
    /**
     * 
     */
    data: Array<ThreadResponseDto>;
    /**
     * 
     */
    meta: PaginationMetaDto;
}

/**
 * Check if a given object implements the PaginatedThreadsResponseDto interface.
 */
export function instanceOfPaginatedThreadsResponseDto(value: object): value is PaginatedThreadsResponseDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function PaginatedThreadsResponseDtoFromJSON(json: any): PaginatedThreadsResponseDto {
    return PaginatedThreadsResponseDtoFromJSONTyped(json, false);
}

export function PaginatedThreadsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedThreadsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ThreadResponseDtoFromJSON)),
        'meta': PaginationMetaDtoFromJSON(json['meta']),
    };
}

export function PaginatedThreadsResponseDtoToJSON(json: any): PaginatedThreadsResponseDto {
    return PaginatedThreadsResponseDtoToJSONTyped(json, false);
}

export function PaginatedThreadsResponseDtoToJSONTyped(value?: PaginatedThreadsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ThreadResponseDtoToJSON)),
        'meta': PaginationMetaDtoToJSON(value['meta']),
    };
}

