/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { CommentResponseDto } from './CommentResponseDto';
import {
    CommentResponseDtoFromJSON,
    CommentResponseDtoFromJSONTyped,
    CommentResponseDtoToJSON,
    CommentResponseDtoToJSONTyped,
} from './CommentResponseDto';

/**
 * 
 * @export
 * @interface ThreadWithCommentsResponseDto
 */
export interface ThreadWithCommentsResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    body: string;
    /**
     * 
     */
    authorId: string;
    /**
     * 
     */
    author: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    comments: Array<CommentResponseDto>;
}

/**
 * Check if a given object implements the ThreadWithCommentsResponseDto interface.
 */
export function instanceOfThreadWithCommentsResponseDto(value: object): value is ThreadWithCommentsResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('comments' in value) || value['comments'] === undefined) return false;
    return true;
}

export function ThreadWithCommentsResponseDtoFromJSON(json: any): ThreadWithCommentsResponseDto {
    return ThreadWithCommentsResponseDtoFromJSONTyped(json, false);
}

export function ThreadWithCommentsResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadWithCommentsResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'body': json['body'],
        'authorId': json['authorId'],
        'author': json['author'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
        'comments': ((json['comments'] as Array<any>).map(CommentResponseDtoFromJSON)),
    };
}

export function ThreadWithCommentsResponseDtoToJSON(json: any): ThreadWithCommentsResponseDto {
    return ThreadWithCommentsResponseDtoToJSONTyped(json, false);
}

export function ThreadWithCommentsResponseDtoToJSONTyped(value?: ThreadWithCommentsResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'body': value['body'],
        'authorId': value['authorId'],
        'author': value['author'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'comments': ((value['comments'] as Array<any>).map(CommentResponseDtoToJSON)),
    };
}

