/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ThreadResponseDto
 */
export interface ThreadResponseDto {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    body: string;
    /**
     * 
     */
    authorId: string;
    /**
     * 
     */
    author: string;
    /**
     * 
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ThreadResponseDto interface.
 */
export function instanceOfThreadResponseDto(value: object): value is ThreadResponseDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ThreadResponseDtoFromJSON(json: any): ThreadResponseDto {
    return ThreadResponseDtoFromJSONTyped(json, false);
}

export function ThreadResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'body': json['body'],
        'authorId': json['authorId'],
        'author': json['author'],
        'createdAt': (json['createdAt'] == null ? json['createdAt'] : parseDateTime(json['createdAt'])),
    };
}

export function ThreadResponseDtoToJSON(json: any): ThreadResponseDto {
    return ThreadResponseDtoToJSONTyped(json, false);
}

export function ThreadResponseDtoToJSONTyped(value?: ThreadResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'body': value['body'],
        'authorId': value['authorId'],
        'author': value['author'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

