packages:
  - 'apps/0[1-8]-*'
  - 'apps/0[1-8]-*/*'
  - 'apps/0[1-8]-*/*/*'
  - 'apps/00-side-projects/*'
  - 'bootcamp/*'
  - 'bootcamp/*/*'
  - 'bootcamp/*/*/*'
  - 'bootcamp/*/*/*/*'
  - 'packages/*'
  - 'playgrounds/*'
  - '!**/.deploy/**'
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': false
  '@swc/core': true
  bcrypt: true
  better-sqlite3: true
  esbuild: true
  protobufjs: false
  sharp: false
  sqlite3: true
  unrs-resolver: false
