/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CommentResponseDto,
    CommentResponseDtoFromJSON,
    CommentResponseDtoToJSON,
} from '../models/CommentResponseDto';

export interface CommentsControllerGetOneRequest {
    /**
     * 
     */
    id: string;
}

export interface CommentsControllerRemoveRequest {
    /**
     * 
     */
    id: string;
}

export interface CommentsControllerUpdateRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    body: object;
}

/**
 * 
 */
export class CommentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for commentsControllerGetOne without sending the request
     */
    async commentsControllerGetOneRequestOpts(requestParameters: CommentsControllerGetOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling commentsControllerGetOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/comments/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single comment by id
     */
    async commentsControllerGetOneRaw(requestParameters: CommentsControllerGetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentResponseDto>> {
        const requestOptions = await this.commentsControllerGetOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a single comment by id
     */
    async commentsControllerGetOne(requestParameters: CommentsControllerGetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentResponseDto> {
        const response = await this.commentsControllerGetOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for commentsControllerRemove without sending the request
     */
    async commentsControllerRemoveRequestOpts(requestParameters: CommentsControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling commentsControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/comments/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a comment you own
     */
    async commentsControllerRemoveRaw(requestParameters: CommentsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.commentsControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a comment you own
     */
    async commentsControllerRemove(requestParameters: CommentsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.commentsControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for commentsControllerUpdate without sending the request
     */
    async commentsControllerUpdateRequestOpts(requestParameters: CommentsControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling commentsControllerUpdate().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling commentsControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/comments/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update a comment you own
     */
    async commentsControllerUpdateRaw(requestParameters: CommentsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentResponseDto>> {
        const requestOptions = await this.commentsControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update a comment you own
     */
    async commentsControllerUpdate(requestParameters: CommentsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentResponseDto> {
        const response = await this.commentsControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
