/* tslint:disable */
/* eslint-disable */
/**
 * Cyber Chat API
 * Threads, comments, and users with JWT authentication
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CommentResponseDto,
    CommentResponseDtoFromJSON,
    CommentResponseDtoToJSON,
} from '../models/CommentResponseDto';
import {
    type CreateCommentDto,
    CreateCommentDtoFromJSON,
    CreateCommentDtoToJSON,
} from '../models/CreateCommentDto';
import {
    type CreateThreadDto,
    CreateThreadDtoFromJSON,
    CreateThreadDtoToJSON,
} from '../models/CreateThreadDto';
import {
    type PaginatedThreadsResponseDto,
    PaginatedThreadsResponseDtoFromJSON,
    PaginatedThreadsResponseDtoToJSON,
} from '../models/PaginatedThreadsResponseDto';
import {
    type ThreadResponseDto,
    ThreadResponseDtoFromJSON,
    ThreadResponseDtoToJSON,
} from '../models/ThreadResponseDto';
import {
    type ThreadWithCommentsResponseDto,
    ThreadWithCommentsResponseDtoFromJSON,
    ThreadWithCommentsResponseDtoToJSON,
} from '../models/ThreadWithCommentsResponseDto';

export interface ThreadsControllerAddCommentRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    createCommentDto: CreateCommentDto;
}

export interface ThreadsControllerCreateRequest {
    /**
     * 
     */
    createThreadDto: CreateThreadDto;
}

export interface ThreadsControllerGetAllRequest {
    /**
     * Page number (default 1)
     */
    page?: number;
    /**
     * Page size, 1-100 (default 10)
     */
    limit?: number;
    /**
     * 
     */
    sort?: ThreadsControllerGetAllSortEnum;
    /**
     * Filter by author username
     */
    author?: string;
    /**
     * ISO date; only threads created on or after this date
     */
    startDate?: Date;
}

export interface ThreadsControllerGetOneRequest {
    /**
     * 
     */
    id: string;
}

export interface ThreadsControllerRemoveRequest {
    /**
     * 
     */
    id: string;
}

export interface ThreadsControllerUpdateRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    body: object;
}

/**
 * 
 */
export class ThreadsApi extends runtime.BaseAPI {

    /**
     * Creates request options for threadsControllerAddComment without sending the request
     */
    async threadsControllerAddCommentRequestOpts(requestParameters: ThreadsControllerAddCommentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling threadsControllerAddComment().'
            );
        }

        if (requestParameters['createCommentDto'] == null) {
            throw new runtime.RequiredError(
                'createCommentDto',
                'Required parameter "createCommentDto" was null or undefined when calling threadsControllerAddComment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/threads/{id}/comments`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCommentDtoToJSON(requestParameters['createCommentDto']),
        };
    }

    /**
     * Add a comment to a thread
     */
    async threadsControllerAddCommentRaw(requestParameters: ThreadsControllerAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommentResponseDto>> {
        const requestOptions = await this.threadsControllerAddCommentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommentResponseDtoFromJSON(jsonValue));
    }

    /**
     * Add a comment to a thread
     */
    async threadsControllerAddComment(requestParameters: ThreadsControllerAddCommentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommentResponseDto> {
        const response = await this.threadsControllerAddCommentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for threadsControllerCreate without sending the request
     */
    async threadsControllerCreateRequestOpts(requestParameters: ThreadsControllerCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createThreadDto'] == null) {
            throw new runtime.RequiredError(
                'createThreadDto',
                'Required parameter "createThreadDto" was null or undefined when calling threadsControllerCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/threads`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateThreadDtoToJSON(requestParameters['createThreadDto']),
        };
    }

    /**
     * Start a new thread
     */
    async threadsControllerCreateRaw(requestParameters: ThreadsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponseDto>> {
        const requestOptions = await this.threadsControllerCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadResponseDtoFromJSON(jsonValue));
    }

    /**
     * Start a new thread
     */
    async threadsControllerCreate(requestParameters: ThreadsControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponseDto> {
        const response = await this.threadsControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for threadsControllerGetAll without sending the request
     */
    async threadsControllerGetAllRequestOpts(requestParameters: ThreadsControllerGetAllRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['author'] != null) {
            queryParameters['author'] = requestParameters['author'];
        }

        if (requestParameters['startDate'] != null) {
            queryParameters['startDate'] = runtime.serializeDateTime(requestParameters['startDate'] as any);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/threads`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List threads, paginated and optionally filtered
     */
    async threadsControllerGetAllRaw(requestParameters: ThreadsControllerGetAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedThreadsResponseDto>> {
        const requestOptions = await this.threadsControllerGetAllRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedThreadsResponseDtoFromJSON(jsonValue));
    }

    /**
     * List threads, paginated and optionally filtered
     */
    async threadsControllerGetAll(requestParameters: ThreadsControllerGetAllRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedThreadsResponseDto> {
        const response = await this.threadsControllerGetAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for threadsControllerGetOne without sending the request
     */
    async threadsControllerGetOneRequestOpts(requestParameters: ThreadsControllerGetOneRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling threadsControllerGetOne().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/threads/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a single thread with its comments
     */
    async threadsControllerGetOneRaw(requestParameters: ThreadsControllerGetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadWithCommentsResponseDto>> {
        const requestOptions = await this.threadsControllerGetOneRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadWithCommentsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get a single thread with its comments
     */
    async threadsControllerGetOne(requestParameters: ThreadsControllerGetOneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadWithCommentsResponseDto> {
        const response = await this.threadsControllerGetOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for threadsControllerRemove without sending the request
     */
    async threadsControllerRemoveRequestOpts(requestParameters: ThreadsControllerRemoveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling threadsControllerRemove().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/threads/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a thread you own
     */
    async threadsControllerRemoveRaw(requestParameters: ThreadsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.threadsControllerRemoveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a thread you own
     */
    async threadsControllerRemove(requestParameters: ThreadsControllerRemoveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.threadsControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for threadsControllerUpdate without sending the request
     */
    async threadsControllerUpdateRequestOpts(requestParameters: ThreadsControllerUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling threadsControllerUpdate().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling threadsControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/threads/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     * Update a thread you own
     */
    async threadsControllerUpdateRaw(requestParameters: ThreadsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponseDto>> {
        const requestOptions = await this.threadsControllerUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update a thread you own
     */
    async threadsControllerUpdate(requestParameters: ThreadsControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponseDto> {
        const response = await this.threadsControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ThreadsControllerGetAllSortEnum = {
    CreatedAt: 'createdAt',
    CreatedAt2: '-createdAt',
} as const;
export type ThreadsControllerGetAllSortEnum = typeof ThreadsControllerGetAllSortEnum[keyof typeof ThreadsControllerGetAllSortEnum];
