services:
  scoreboard:
    build:
      context: ../../../..
      dockerfile: bootcamp/05-devops/docker-advanced/scoreboard-service/Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
